[package]
name = "hft_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
plotters = "0.3.7"
uuid = { version = "1.3", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
csv = "1.3"
