name: Global Index Report

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance pandas matplotlib

      - name: Run global report
        run: python index-effect/python/global_report.py

      - name: Commit updated PDF
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add buypolarcapital/index-effect/python/plots/global_index_report.pdf
          git commit -m "📘 Update global index report [auto]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 📈 Global Index Report from BuyPolar Capital
          to: ${{ secrets.EMAIL_TO }}
          from: BuyPolar Capital Bot <${{ secrets.EMAIL_ADDRESS }}>
          body: |
            Hi Egil,

            Here is your latest Global Index Report. Stay frosty 🐻‍❄️📈

            - BuyPolar Capital
          attachments: buypolarcapital/index-effect/python/plots/global_index_report.pdf
