name: Global Index Report

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 06:00 UTC
  workflow_dispatch:      # Manual trigger button on GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance pandas matplotlib

      - name: Run global report
        run: |
          python src/buypolarcapital/strategies/ie/python/global_report.py

      - name: Commit updated PDF
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add -f src/buypolarcapital/strategies/ie/python/plots/global_index_report.pdf
          LATEST_DATE=$(date -u '+%Y-%m-%d')
          git commit -m "📘 Update global index report for $LATEST_DATE [auto]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 📈 Global Index Report from BuyPolar Capital
          to: ${{ secrets.EMAIL_TO }}
          from: BuyPolar Capital Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hi Egil,

            Here is your latest Global Index Report. Stay frosty 🐻‍❄️📈

            - BuyPolar Capital
          attachments: src/buypolarcapital/strategies/ie/python/plots/global_index_report.pdf
